---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(ggplot2)
```


```{r}
set.seed(123)

n = 200 # sample
samples = seq(from=150,to=800,by=50)
effect.sizes <- seq(0.05, 0.4, by = 0.05)  # range of effect sizes to test
alpha <- 0.05  # alpha level for significance

iter=1000

powerPerEffect <- numeric(length(effect.sizes)) # effect size power

n_b=1 # beginning index
n_e=8 # end index

powerTotal = matrix(ncol=3,nrow=length(powerPerEffect)*length(samples)) # full power

for(N in seq_along(samples)){
  n = samples[N]
  for (i in seq_along(effect.sizes)) {
  power <- vector(length=iter)
  for(t in 1:iter){
  # simulate data
  x1 <- rnorm(n, mean = 0, sd = 1)
  x2 <- rnorm(n, mean = 0, sd = 1)
  x3 <- rnorm(n, mean = 0, sd = 1)
  x4 <- rnorm(n, mean = 0, sd = 1)
  y <- 1 + x1 + x2 + x3 + x4 + x1*x2 + x1*x3 + x2*x3 + x1*x4 + x2*x4 + x3*x4 + x1*x2*x3 + x1*x2*x4 + x2*x3*x4 + x2*x3*x4 + effect.sizes[i]*x1*x2*x3*x4 + rnorm(n, mean = 0, sd = 1)
  df=data.frame(y=y,x1=x1,x2=x2,x3=x3,x4=x4)
  
  # fit model
  model <- lm(y ~ x1*x2*x3*x4,data=df)
  
  # test for significance of four-way interaction
  p.value <- summary(model)$coefficients["x1:x2:x3:x4", "Pr(>|t|)"]
  if (p.value < alpha) {
    power[t] <- 1 # if it is sig, it is a "true positive", store it
  }
  }
  powerPerEffect[i] = mean(power)
  }
  powerTotal[n_b:n_e,1:3] <- cbind(n,powerPerEffect,effect.sizes)
  n_b=n_b+8 # increment up
  n_e=n_e+8 # increment up
}

powerTotal <- as.data.frame(powerTotal)
colnames(powerTotal) <- c("N","Power","ES")
```

```{r}
ggplot(powerTotal, aes(x=N, y=Power, color=as.factor(ES) )) +
    geom_line() + geom_hline(yintercept=.8, linetype="dashed")
```


